using System.Globalization;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using TinyWin.Core.Abstractions;
using static TinyWin.Unattend.UnattendSchema;

namespace TinyWin.Unattend;

/// <summary>
/// Renders <c>autounattend.xml</c> for Windows 11 (24H2 / 25H2) from <see cref="UnattendOptions"/>.
/// </summary>
/// <remarks>
/// <para>
/// Pure and deterministic: the same options and architecture always produce byte-identical output,
/// which is what makes the golden-file suite in <c>tests/TinyWin.Tests/Golden/Unattend</c> worth
/// anything. Nothing here touches the filesystem, the clock, the host registry or the current
/// culture.
/// </para>
/// <para>
/// Only settings the caller actually asked for are emitted. In particular this file never contains
/// <c>DiskConfiguration</c>, <c>ImageInstall</c> or <c>UserData/ProductKey</c>: TinyWin does not
/// partition the user's disk, does not choose their edition for them and does not touch licensing
/// (see <c>docs/PLAN.md</c> §1). An empty <see cref="UnattendOptions"/> therefore yields a file
/// with no <c>settings</c> elements at all, and Setup behaves exactly as it would with no answer
/// file present.
/// </para>
/// <para>
/// <b>Security:</b> <see cref="LocalAccountOptions.Password"/> is written to exactly one place —
/// the <c>LocalAccount/Password/Value</c> element of the returned string. It is never logged, never
/// interpolated into an exception message and never round-tripped into a preset.
/// </para>
/// </remarks>
public sealed class UnattendGenerator : IUnattendGenerator
{
    // HKLM\SYSTEM\Setup\LabConfig is read by Setup's compatibility check while it is still running
    // under WinPE, which is why these are written in the windowsPE pass rather than specialize.
    private const string LabConfigKey = @"HKLM\SYSTEM\Setup\LabConfig";

    // Read by OOBE when it decides whether the "Sign in with Microsoft" screen is mandatory.
    private const string OobeKey = @"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE";

    // The policy branch OOBE consults for the privacy questionnaire.
    private const string OobePolicyKey = @"HKLM\SOFTWARE\Policies\Microsoft\Windows\OOBE";

    // Checked before Windows 11 silently turns on device encryption at the end of OOBE.
    private const string BitLockerKey = @"HKLM\SYSTEM\CurrentControlSet\Control\BitLocker";

    // Line endings are spelled out rather than taken from a raw string literal so the banner is
    // CRLF on every build host, and the output stays pure ASCII.
    private const string GeneratedBanner =
        "\r\n    Generated by TinyWin - https://github.com/mrzcookie/tinywin\r\n"
        + "    Regenerate from the app rather than editing this file by hand.\r\n";

    /// <inheritdoc />
    public string Generate(UnattendOptions options, string architecture)
    {
        ArgumentNullException.ThrowIfNull(options);

        var arch = UnattendValidation.NormalizeArchitecture(architecture);
        var uiLanguage = UnattendValidation.ValidateLocale(options.UiLanguage, nameof(UnattendOptions.UiLanguage));
        var timeZone = UnattendValidation.ValidateTimeZone(options.TimeZone);
        var account = UnattendValidation.ValidateLocalAccount(options.LocalAccount);

        // The default namespace is declared explicitly so it is written before xmlns:wcm, matching
        // what Windows System Image Manager produces. Namespace declarations are unordered as far
        // as XML is concerned; this only makes the file easier to diff against a WSIM-authored one.
        var root = new XElement(
            Ns + "unattend",
            new XAttribute("xmlns", Ns.NamespaceName),
            new XAttribute(XNamespace.Xmlns + "wcm", Wcm.NamespaceName));

        AddSettings(root, WindowsPePass, BuildWindowsPe(options, arch, uiLanguage));
        AddSettings(root, SpecializePass, BuildSpecialize(options, arch));
        AddSettings(root, OobeSystemPass, BuildOobeSystem(options, arch, uiLanguage, timeZone, account));

        var document = new XDocument(new XComment(GeneratedBanner), root);
        return Serialize(document);
    }

    private static void AddSettings(XElement root, string pass, IEnumerable<XElement> components)
    {
        var materialised = components.ToList();
        if (materialised.Count == 0)
        {
            return;
        }

        root.Add(new XElement(Ns + "settings", new XAttribute("pass", pass), materialised));
    }

    // ---------------------------------------------------------------------------------------
    // windowsPE — runs inside the Setup boot environment, before the image is applied.
    // ---------------------------------------------------------------------------------------

    private static IEnumerable<XElement> BuildWindowsPe(UnattendOptions options, string arch, string? uiLanguage)
    {
        // Components are emitted in the order Windows System Image Manager writes them, which is
        // alphabetical by component name.
        if (uiLanguage is not null)
        {
            yield return Component(
                InternationalCoreWinPe,
                arch,
                // SetupUILanguage drives the Setup UI itself; the four siblings seed the installed OS.
                new XElement(Ns + "SetupUILanguage", new XElement(Ns + "UILanguage", uiLanguage)),
                new XElement(Ns + "InputLocale", uiLanguage),
                new XElement(Ns + "SystemLocale", uiLanguage),
                new XElement(Ns + "UILanguage", uiLanguage),
                new XElement(Ns + "UserLocale", uiLanguage));
        }

        var bypasses = new List<(bool Enabled, string ValueName, string Description)>
        {
            (options.BypassTpmCheck, "BypassTPMCheck", "Bypass the TPM 2.0 requirement"),
            (options.BypassSecureBootCheck, "BypassSecureBootCheck", "Bypass the Secure Boot requirement"),
            (options.BypassRamCheck, "BypassRAMCheck", "Bypass the 4 GB RAM requirement"),
            (options.BypassCpuCheck, "BypassCPUCheck", "Bypass the supported-processor requirement"),
            (options.BypassStorageCheck, "BypassStorageCheck", "Bypass the 64 GB system drive requirement"),
        };

        var enabled = bypasses.Where(b => b.Enabled).ToList();
        if (enabled.Count == 0)
        {
            yield break;
        }

        var commands = enabled.Select((b, index) => SetupCommand(
            order: index + 1,
            path: RegistryCommand.AddDword(LabConfigKey, b.ValueName, 1),
            description: b.Description));

        yield return Component(Setup, arch, new XElement(Ns + "RunSynchronous", commands));
    }

    // ---------------------------------------------------------------------------------------
    // specialize — runs in the installed OS, in system context, before OOBE starts.
    // ---------------------------------------------------------------------------------------

    private static IEnumerable<XElement> BuildSpecialize(UnattendOptions options, string arch)
    {
        var commands = new List<(string Path, string Description)>();

        if (options.AllowLocalAccount)
        {
            // The unattend LocalAccount below is what actually creates the account; this is the
            // belt to its braces, and the only thing that helps when no account was supplied and
            // the user still wants the local-account path through OOBE. Microsoft removed the
            // bypassnro.cmd script from 26200 media, but honours the value it used to write.
            commands.Add((
                RegistryCommand.AddDword(OobeKey, "BypassNRO", 1),
                "Allow finishing setup without a Microsoft account"));
        }

        if (options.SkipPrivacySettings)
        {
            commands.Add((
                RegistryCommand.AddDword(OobePolicyKey, "DisablePrivacyExperience", 1),
                "Skip the OOBE privacy settings screens"));
        }

        if (options.PreventDeviceEncryption)
        {
            // Windows 11 24H2 turns device encryption on by default at the end of OOBE. Without
            // this the recovery key is escrowed to whatever account signs in first, which is a
            // nasty surprise on a machine built from custom media.
            commands.Add((
                RegistryCommand.AddDword(BitLockerKey, "PreventDeviceEncryption", 1),
                "Prevent automatic BitLocker device encryption"));
        }

        if (commands.Count == 0)
        {
            yield break;
        }

        var elements = commands.Select((c, index) => DeploymentCommand(
            order: index + 1,
            path: c.Path,
            description: c.Description));

        yield return Component(Deployment, arch, new XElement(Ns + "RunSynchronous", elements));
    }

    // ---------------------------------------------------------------------------------------
    // oobeSystem — the last pass before the first-boot experience.
    // ---------------------------------------------------------------------------------------

    private static IEnumerable<XElement> BuildOobeSystem(
        UnattendOptions options,
        string arch,
        string? uiLanguage,
        string? timeZone,
        LocalAccountOptions? account)
    {
        if (uiLanguage is not null)
        {
            yield return Component(
                InternationalCore,
                arch,
                new XElement(Ns + "InputLocale", uiLanguage),
                new XElement(Ns + "SystemLocale", uiLanguage),
                new XElement(Ns + "UILanguage", uiLanguage),
                new XElement(Ns + "UserLocale", uiLanguage));
        }

        // OOBE children follow the schema's alphabetical order.
        var oobeChildren = new List<XElement>();

        if (options.SkipOemRegistration)
        {
            oobeChildren.Add(new XElement(Ns + "HideOEMRegistrationScreen", "true"));
        }

        if (options.AllowLocalAccount)
        {
            oobeChildren.Add(new XElement(Ns + "HideOnlineAccountScreens", "true"));
        }

        if (options.SkipPrivacySettings)
        {
            // 3 is the only documented value that turns Express settings off.
            oobeChildren.Add(new XElement(Ns + "ProtectYourPC", "3"));
        }

        var shellChildren = new List<XElement>();

        if (oobeChildren.Count > 0)
        {
            shellChildren.Add(new XElement(Ns + "OOBE", oobeChildren));
        }

        if (account is not null)
        {
            shellChildren.Add(LocalAccounts(account));
        }

        if (timeZone is not null)
        {
            shellChildren.Add(new XElement(Ns + "TimeZone", timeZone));
        }

        if (shellChildren.Count > 0)
        {
            yield return Component(ShellSetup, arch, shellChildren);
        }
    }

    private static XElement LocalAccounts(LocalAccountOptions account)
    {
        // Child order matches the schema: Password, Description, DisplayName, Group, Name.
        var children = new List<XElement>();

        // Written even for a passwordless account: an explicit empty Value is what tells OOBE not
        // to stop and ask for one, whereas an absent Password element is only conventionally
        // understood to mean the same thing.
        //
        // PlainText=true is deliberate. The alternative encoding is base64 of UTF-16LE with the
        // element name appended — obfuscation, not encryption, trivially reversed and easy to get
        // subtly wrong. An answer file carrying a password is sensitive either way; the honest
        // spelling is the one Setup can never misread.
        children.Add(new XElement(
            Ns + "Password",
            new XElement(Ns + "Value", account.Password ?? string.Empty),
            new XElement(Ns + "PlainText", "true")));

        if (account.DisplayName is { } displayName)
        {
            children.Add(new XElement(Ns + "DisplayName", displayName));
        }

        children.Add(new XElement(Ns + "Group", "Administrators"));
        children.Add(new XElement(Ns + "Name", account.Username));

        return new XElement(
            Ns + "UserAccounts",
            new XElement(
                Ns + "LocalAccounts",
                new XElement(Ns + "LocalAccount", new XAttribute(Wcm + "action", "add"), children)));
    }

    // ---------------------------------------------------------------------------------------
    // Element helpers
    // ---------------------------------------------------------------------------------------

    private static XElement Component(string name, string arch, params object[] content) =>
        new(
            Ns + "component",
            new XAttribute("name", name),
            new XAttribute("processorArchitecture", arch),
            new XAttribute("publicKeyToken", PublicKeyToken),
            new XAttribute("language", Language),
            new XAttribute("versionScope", VersionScope),
            content);

    /// <summary>Microsoft-Windows-Setup documents its command children as Order, Path, Description.</summary>
    private static XElement SetupCommand(int order, string path, string description) =>
        new(
            Ns + "RunSynchronousCommand",
            new XAttribute(Wcm + "action", "add"),
            new XElement(Ns + "Order", order.ToString(CultureInfo.InvariantCulture)),
            new XElement(Ns + "Path", path),
            new XElement(Ns + "Description", description));

    /// <summary>Microsoft-Windows-Deployment documents its command children alphabetically.</summary>
    private static XElement DeploymentCommand(int order, string path, string description) =>
        new(
            Ns + "RunSynchronousCommand",
            new XAttribute(Wcm + "action", "add"),
            new XElement(Ns + "Description", description),
            new XElement(Ns + "Order", order.ToString(CultureInfo.InvariantCulture)),
            new XElement(Ns + "Path", path));

    private static string Serialize(XDocument document)
    {
        var settings = new XmlWriterSettings
        {
            Indent = true,
            IndentChars = "    ",
            // Fixed rather than Environment.NewLine so a Linux build agent and a Windows one
            // produce the same bytes. CRLF because this file is read by Windows Setup.
            NewLineChars = "\r\n",
            NewLineHandling = NewLineHandling.Replace,
            OmitXmlDeclaration = false,
            Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
        };

        using var writer = new Utf8StringWriter();
        using (var xml = XmlWriter.Create(writer, settings))
        {
            document.Save(xml);
        }

        return writer.ToString();
    }

    /// <summary>
    /// A <see cref="StringWriter"/> that claims UTF-8, so the XML declaration reads
    /// <c>encoding="utf-8"</c> instead of the <c>utf-16</c> a plain StringWriter would produce.
    /// Windows Setup will not read an answer file that declares UTF-16 but is written as UTF-8.
    /// </summary>
    private sealed class Utf8StringWriter() : StringWriter(CultureInfo.InvariantCulture)
    {
        public override Encoding Encoding { get; } = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
    }
}
